-- Seed initial test users
-- All users have password: 'password123' (hashed with bcrypt)
-- These are for testing purposes only

-- Note: Password hashes will be generated by the init-db script
-- This file serves as documentation for the default test accounts

-- Default users:
-- 1. Gary (gary)
-- 2. Neave (neave)
-- 3. Harish (harish)
-- 4. Chris (chris)
-- 5. Tony (tony)
-- 6. Seymour (seymour)
-- 7. Kerwin (kerwin)
-- 8. Wayne (wayne)
-- 9. Dee (dee)
-- 10. Lorenzo (lorenzo)

INSERT INTO users (display_name, user_name) VALUES
('Gary', 'gary'),
('Neave', 'neave'),
('Harish', 'harish'),
('Chris', 'chris'),
('Tony', 'tony'),
('Seymour', 'seymour'),
('Kerwin', 'kerwin'),
('Wayne', 'wayne'),
('Dee', 'dee'),
('Lorenzo', 'lorenzo'),
('JB', 'jb');
