-- Seed initial test users
-- All users have password: 'password123' (hashed with bcrypt)
-- These are for testing purposes only

-- Note: Password hashes will be generated by the init-db script
-- This file serves as documentation for the default test accounts

-- Default users:
-- 1. Alice (alice@example.com)
-- 2. Bob (bob@example.com)
-- 3. Charlie (charlie@example.com)
-- 4. Diana (diana@example.com)
-- 5. Eve (eve@example.com)
-- 6. Frank (frank@example.com)
-- 7. Grace (grace@example.com)
-- 8. Henry (henry@example.com)
-- 9. Ivy (ivy@example.com)
-- 10. Jack (jack@example.com)

-- All with password: password123
